### ISSUE TITLE
can't install: invalid tar header checksum

### ISSUE THREAD

**Issue by konsumer** [emscripten-core/emsdk#1143]
I cannot install on alpine/aarch64:

```
docker run --rm -it alpine

apk add --no-cache git python3
git clone --depth=1 https://github.com/emscripten-core/emsdk.git /emsdk
cd /emsdk
./emsdk install latest
```

```
warning: 'latest' on arm64-linux may be slightly behind other architectures
Resolving SDK alias 'latest-arm64-linux' to '3.1.21'
Resolving SDK version '3.1.21' to 'sdk-releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'
Installing SDK 'sdk-releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'..
Skipped installing node-14.18.2-64bit, already installed.
Installing tool 'releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'..
Downloading: /emsdk/zips/a16a8bca2466eb144f7c93fa899c0272c8815dc3-wasm-binaries-arm64.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/a16a8bca2466eb144f7c93fa899c0272c8815dc3/wasm-binaries-arm64.tbz2, 237396459 Bytes
Unpacking '/emsdk/zips/a16a8bca2466eb144f7c93fa899c0272c8815dc3-wasm-binaries-arm64.tbz2' to '/emsdk/upstream'
tar: invalid tar header checksum
['tar', '-xf', '/emsdk/zips/a16a8bca2466eb144f7c93fa899c0272c8815dc3-wasm-binaries-arm64.tbz2', '--strip', '1'] failed with error code 1!
error: installation failed!
```

**Comment by konsumer** [comment]
Same on debian:

```
docker run --rm -it debian:bullseye

apt update
apt install -y git python-is-python3
./emsdk install latest
```

```
warning: 'latest' on arm64-linux may be slightly behind other architectures
Resolving SDK alias 'latest-arm64-linux' to '3.1.21'
Resolving SDK version '3.1.21' to 'sdk-releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'
Installing SDK 'sdk-releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'..
Installing tool 'node-14.18.2-64bit'..
Downloading: /emsdk/zips/node-v14.18.2-linux-arm64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.18.2-linux-arm64.tar.xz, 21134636 Bytes
Unpacking '/emsdk/zips/node-v14.18.2-linux-arm64.tar.xz' to '/emsdk/node/14.18.2_64bit'
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
['tar', '-xf', '/emsdk/zips/node-v14.18.2-linux-arm64.tar.xz', '--strip', '1'] failed with error code 2!
error: installation failed!
```

**Comment by konsumer** [comment]
Seems to work fine on x86_64:

```
docker run --platform=linux/amd64 --rm -it alpine

apk add --no-cache git python3
git clone --depth=1 https://github.com/emscripten-core/emsdk.git /emsdk
cd /emsdk
./emsdk install latest
```

```
Resolving SDK alias 'latest' to '3.1.27'
Resolving SDK version '3.1.27' to 'sdk-releases-upstream-48ce0b44015d0182fc8c27aa9fbc0a4474b55982-64bit'
Installing SDK 'sdk-releases-upstream-48ce0b44015d0182fc8c27aa9fbc0a4474b55982-64bit'..
Installing tool 'node-14.18.2-64bit'..
Downloading: /emsdk/zips/node-v14.18.2-linux-x64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.18.2-linux-x64.tar.xz, 21848416 Bytes
Unpacking '/emsdk/zips/node-v14.18.2-linux-x64.tar.xz' to '/emsdk/node/14.18.2_64bit'
Done installing tool 'node-14.18.2-64bit'.
Installing tool 'releases-upstream-48ce0b44015d0182fc8c27aa9fbc0a4474b55982-64bit'..
Downloading: /emsdk/zips/48ce0b44015d0182fc8c27aa9fbc0a4474b55982-wasm-binaries.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/48ce0b44015d0182fc8c27aa9fbc0a4474b55982/wasm-binaries.tbz2, 371163051 Bytes
Unpacking '/emsdk/zips/48ce0b44015d0182fc8c27aa9fbc0a4474b55982-wasm-binaries.tbz2' to '/emsdk/upstream'
Done installing tool 'releases-upstream-48ce0b44015d0182fc8c27aa9fbc0a4474b55982-64bit'.
Done installing SDK 'sdk-releases-upstream-48ce0b44015d0182fc8c27aa9fbc0a4474b55982-64bit'.
```

**Comment by sbc100** [comment]
> Same on debian:
> 
> ```
> docker run --rm -it debian
> 
> apt update
> apt install -y git python-is-python3
> 
> git clone --depth=1 https://github.com/emscripten-core/emsdk.git /emsdk
> cd /emsdk
> ./emsdk install latest
> ```
> 
> ```
> warning: 'latest' on arm64-linux may be slightly behind other architectures
> Resolving SDK alias 'latest-arm64-linux' to '3.1.21'
> Resolving SDK version '3.1.21' to 'sdk-releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'
> Installing SDK 'sdk-releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'..
> Installing tool 'node-14.18.2-64bit'..
> Downloading: /emsdk/zips/node-v14.18.2-linux-arm64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.18.2-linux-arm64.tar.xz, 21134636 Bytes
> Unpacking '/emsdk/zips/node-v14.18.2-linux-arm64.tar.xz' to '/emsdk/node/14.18.2_64bit'
> tar (child): xz: Cannot exec: No such file or directory
> tar (child): Error is not recoverable: exiting now
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
> ['tar', '-xf', '/emsdk/zips/node-v14.18.2-linux-arm64.tar.xz', '--strip', '1'] failed with error code 2!
> error: installation failed!
> ```

At least in this case the issues is that you `tar` executable can't extract `xz` files (`tar (child): xz: Cannot exec: No such file or directory`).  It looks like its trying to fork and `xz` subproccess to do it and `xz` is missing.  

Looks like that `tar` package only "Suggests" that you have `xz-utils` installed:

```
$ dpkg -s tar
...
Suggests: bzip2, ncompress, xz-utils, tar-scripts, tar-doc
...
```

`apt-get install xz-utils` should fix it.

**Comment by konsumer** [comment]
This only happens on arm64, and happens on alpine and debian both (it's not specific to the tarversion.) It still happens, following your suggestion:

```
docker run --rm -it debian

apt update
apt install -y git python-is-python3 xz-utils

git clone --depth=1 https://github.com/emscripten-core/emsdk.git /emsdk
cd /emsdk
./emsdk install latest
```

```
warning: 'latest' on arm64-linux may be slightly behind other architectures
Resolving SDK alias 'latest-arm64-linux' to '3.1.21'
Resolving SDK version '3.1.21' to 'sdk-releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'
Installing SDK 'sdk-releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'..
Installing tool 'node-14.18.2-64bit'..
Downloading: /emsdk/zips/node-v14.18.2-linux-arm64.tar.xz from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v14.18.2-linux-arm64.tar.xz, 21134636 Bytes
Unpacking '/emsdk/zips/node-v14.18.2-linux-arm64.tar.xz' to '/emsdk/node/14.18.2_64bit'
Done installing tool 'node-14.18.2-64bit'.
Installing tool 'releases-upstream-a16a8bca2466eb144f7c93fa899c0272c8815dc3-64bit'..
Downloading: /emsdk/zips/a16a8bca2466eb144f7c93fa899c0272c8815dc3-wasm-binaries-arm64.tbz2 from https://storage.googleapis.com/webassembly/emscripten-releases-builds/linux/a16a8bca2466eb144f7c93fa899c0272c8815dc3/wasm-binaries-arm64.tbz2, 237396459 Bytes
Unpacking '/emsdk/zips/a16a8bca2466eb144f7c93fa899c0272c8815dc3-wasm-binaries-arm64.tbz2' to '/emsdk/upstream'
tar (child): lbzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
['tar', '-xf', '/emsdk/zips/a16a8bca2466eb144f7c93fa899c0272c8815dc3-wasm-binaries-arm64.tbz2', '--strip', '1'] failed with error code 2!
error: installation failed!
```

**Comment by konsumer** [comment]
I will close this (my original issue is resolved) but make another issue for checking more stuff is installed.
