### ISSUE TITLE
"Cannot create a file when that file already exists."

### ISSUE THREAD

**Issue by Morilli** [emscripten-core/emsdk#286]
I have already installed emscripten using the proper ``.\emsdk install latest`` command. Although I noticed that running it again results in an error that (translated) reads:
``Unzipping file [...] failed due to reason: [Error 183] Cannot create a file when that file already exists.
Installation failed!``

This error does not make sense, as it is talking about the file that was *just downloaded*. See command-line output below.

```
PS G:\Dokumente\GitHub\emsdk> .\emsdk install latest
Installing SDK 'sdk-releases-fastcomp-d46be49c2aab975333423122239892bd46f52bba-64bit'..
Installing tool 'releases-fastcomp-d46be49c2aab975333423122239892bd46f52bba-64bit'..
Downloading: G:/Dokumente/GitHub/emsdk/zips/d46be49c2aab975333423122239892bd46f52bba-wasm-binaries.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/d46be49c2aab975333423122239892bd46f52bba/wasm-binaries.zip, 727298242 Bytes
Unpacking 'G:/Dokumente/GitHub/emsdk/zips/d46be49c2aab975333423122239892bd46f52bba-wasm-binaries.zip' to 'G:/Dokumente/GitHub/emsdk/fastcomp'
Unzipping file 'G:/Dokumente/GitHub/emsdk/zips/d46be49c2aab975333423122239892bd46f52bba-wasm-binaries.zip' failed due to reason: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist
Installation failed!
```

The only thing I could imagine is that it tries to overwrite the existing install and fails at that? I know doing exactly that I'm doing rn (repeatedly using ``.\emsdk install latest`` to update) has worked in the past, so I don't know why it's not working now.

**Comment by kripken** [comment]
Do you have a full python stack trace? That might have more info.

Running `emsdk install latest` multiple times doesn't fail for me locally. I tested on linux, which OS are you on (maybe the bug is specific to an OS)?

**Comment by Morilli** [comment]
I am using the most current version of Windows 10 (Version 10.0.18362.207). What I sent is the entire output on console, how would I create / capture a full stacktrace?

**Comment by kripken** [comment]
Oh, I think the emsdk script hides the stack trace. Removing that with this should show more details:
```
diff --git a/emsdk b/emsdk
index 62c495a..258ce43 100755
--- a/emsdk
+++ b/emsdk
@@ -503,9 +503,6 @@ def unzip(source_filename, dest_dir, unpack_even_if_exists=False):
     print("Unzipping file '" + source_filename + "' failed due to reason: " + str(e) + "! Removing the corrupted zip file.")
     rmfile(source_filename)
     return False
-  except Exception as e:
-    print("Unzipping file '" + source_filename + "' failed due to reason: " + str(e))
-    return False
 
   return True
 
```

**Comment by Morilli** [comment]
I applied that change and also manually set the ``VERBOSE`` variable in the script to True, in case that helps:
```
PS G:\Dokumente\GitHub\emsdk> ./emsdk install latest
CMAKE_GENERATOR: Visual Studio 14
Tool clang-e1.37.1-64bit already existed in manifest, not adding twice
Tool emscripten-1.37.1 already existed in manifest, not adding twice
SDK sdk-1.37.1-64bit already existed in manifest, not adding twice
Installing SDK 'sdk-releases-fastcomp-0ca6c49e30bc09c3ccefc867df4196a4b4183441-64bit'..
Installing tool 'releases-fastcomp-0ca6c49e30bc09c3ccefc867df4196a4b4183441-64bit'..
download_and_unzip(zipfile=https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/0ca6c49e30bc09c3ccefc867df4196a4b4183441/wasm-binaries.zip, dest_dir=G:/Dokumente/GitHub/emsdk/fastcomp)
The contents of file 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/0ca6c49e30bc09c3ccefc867df4196a4b4183441/wasm-binaries.zip' already exist in destination 'G:/Dokumente/GitHub/emsdk/fastcomp', skipping.
Done installing tool 'releases-fastcomp-0ca6c49e30bc09c3ccefc867df4196a4b4183441-64bit'.
Deleting temporary zip file zips/wasm-binaries.zip
rmfile(zips/wasm-binaries.zip)
Installing tool 'node-8.9.1-64bit'..
download_and_unzip(zipfile=node-v8.9.1-win-x64.zip, dest_dir=G:/Dokumente/GitHub/emsdk/node/8.9.1_64bit)
download_file(url=https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v8.9.1-win-x64.zip, dstpath=zips/)
mkdir_p(G:/Dokumente/GitHub/emsdk/zips)
Downloading: G:/Dokumente/GitHub/emsdk/zips/node-v8.9.1-win-x64.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/node-v8.9.1-win-x64.zip, 16940179 Bytes
unzip(source_filename=G:/Dokumente/GitHub/emsdk/zips/node-v8.9.1-win-x64.zip, dest_dir=G:/Dokumente/GitHub/emsdk/node/8.9.1_64bit)
Unpacking 'G:/Dokumente/GitHub/emsdk/zips/node-v8.9.1-win-x64.zip' to 'G:/Dokumente/GitHub/emsdk/node/8.9.1_64bit'
mkdir_p(G:/Dokumente/GitHub/emsdk/node/8.9.1_64bit)
Traceback (most recent call last):
  File "G:\Dokumente\GitHub\emsdk/emsdk", line 2680, in <module>
    sys.exit(main())
  File "G:\Dokumente\GitHub\emsdk/emsdk", line 2662, in main
    success = tool.install()
  File "G:\Dokumente\GitHub\emsdk/emsdk", line 1523, in install
    success = tool.install()
  File "G:\Dokumente\GitHub\emsdk/emsdk", line 1539, in install
    success = download_and_unzip(url, self.installation_path(), download_even_if_exists=download_even_if_exists, filename_prefix=filename_prefix)
  File "G:\Dokumente\GitHub\emsdk/emsdk", line 1108, in download_and_unzip
    return unzip(download_target, dest_dir, unpack_even_if_exists=download_even_if_exists)
  File "G:\Dokumente\GitHub\emsdk/emsdk", line 495, in unzip
    os.rename(fix_potentially_long_windows_pathname(tmp_dst_filename), fix_potentially_long_windows_pathname(final_dst_filename))
WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereits vorhanden ist
```

Again, this only happens after having already run the install command previously, so all files and folders *are already there*. It must be failing to detect that this is the case.
On a somewhat related note, running the command on my WSL did not fail, so this is very likely a Windows-specific issue.

**Comment by kripken** [comment]
Thanks @Morilli - that info is very useful! Yeah, I think this is a windows-specific issue, where `os.rename` behaves differently, and fails on an existing file. I think #294 should fix it, please test.

**Comment by Morilli** [comment]
Two things about that PR:
1. Every second run (it seems like), the installation fails with the following error:
```
Downloading: G:/Dokumente/GitHub/emsdk/zips/WinPython-64bit-2.7.13.1Zero.zip from https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/WinPython-64bit-2.7.13.1Zero.zip, 41285159 Bytes
Unpacking 'G:/Dokumente/GitHub/emsdk/zips/WinPython-64bit-2.7.13.1Zero.zip' to 'G:/Dokumente/GitHub/emsdk/python/2.7.13.1_64bit'
Unzipping file 'G:/Dokumente/GitHub/emsdk/zips/WinPython-64bit-2.7.13.1Zero.zip' failed due to reason: [Error 5] Zugriff verweigert: '\\\\?\\G:\\Dokumente\\GitHub\\emsdk\\python\\2.7.13.1_64bit\\python-2.7.13.amd64\\DLLs\\_ctypes.pyd'
Installation failed!
```
2. Why is it always detecting
```
The contents of file 'https://storage.googleapis.com/webassembly/emscripten-releases-builds/win/0ca6c49e30bc09c3ccefc867df4196a4b4183441/wasm-binaries.zip' already exist in destination 'G:/Dokumente/GitHub/emsdk/fastcomp', skipping.
```
, but never for any of the other zips? Shouldn't it be able to skip every single component if they are already installed?

**Comment by kripken** [comment]
@Morilli - do you still see that first issue even after that PR landed? That looks like the same error message, unless I'm mistaken. Does it also have the same stack trace?

About the second issue, we should check that for all zips, so that sounds like a possible bug. I don't have enough information though - perhaps open a new issue, and provide full steps to see what you are seeing?

**Comment by Morilli** [comment]
The first issue I mentioned was tested on the PR branch, so yes, this still exists.
Here is a log output after a ``git clean -f -f -d -x`` and ``.\emsdk update-tags`` and ``.\emsdk install latest``, running the second ``.\emsdk install latest``:
[temp_needed.txt](https://github.com/emscripten-core/emsdk/files/3386884/temp_needed.txt)
As for the zip check, I can make a new issue for that one.

**Comment by kripken** [comment]
Thanks @Morilli - can you please get the stack trace again, like last time? (Otherwise it's hard to know what exactly is failing, but with the stack trace, it should be clear.)

**Comment by Morilli** [comment]
Right, forgot about that. Here you go: 
[log.txt](https://github.com/emscripten-core/emsdk/files/3394256/log.txt) @kripken

**Comment by kripken** [comment]
Thanks @Morilli - so yes, that's inside the new code, which apparently doesn't work. The code does this:
```
  if os.path.exists(dest):
    os.remove(dest)
  os.rename(src, dest)
```
and it fails on that second line. So the file exists, but it isn't able to remove it? Like maybe it's open in another application or process, or is read-only, or something like that?

**Comment by Morilli** [comment]
I just found out a very important detail: When I run ``.\emsdk install latest``, it will fail **every** second time (every other time it pretends that the ``python`` tool is already installed and therefore doesn't do anything), but running ``python .\emsdk install latest`` makes it work 100% of the time without any errors. I personally have Python 3.7.3 installed.

**Comment by kripken** [comment]
Interesting, good to know python3 works. Would be good to confirm if running `python2 .\emsdk install latest` fails (same command but with python2, if that's installed). If so this sounds like a python2 issue. And maybe we can just require python3, which we want to eventually anyhow.

**Comment by Morilli** [comment]
I don't have python 2 installed, and I also don't really know why explicitly stating ``python`` before running the script makes it work; it must be selecting a wrong / weird version somehow. Requiring python 3 definitely sounds like the only right step, especially regarding https://pythonclock.org/.
