### ISSUE TITLE
emsdk 2.0.13 sdl2_ttf incorrect hash

### ISSUE THREAD

**Issue by HCLJason** [emscripten-core/emsdk#717]
I'm using a fresh checkout, install, and activate of emsdk 2.0.13.

I try to compile a file with em++ -s USE_SDL_TTF=2 <snip other parameters> foo.cpp, and it throws a hash error when downloading and installing the port.

I cleaned my ports cache and tried again, and same result.

system_libs:INFO: retrieving port: sdl2_ttf from https://hg.libsdl.org/SDL_ttf/archive/703ebc7c66fd.zip
em++: error: Unexpected hash: 4c1ac5d27439d28c6d84593dd15dd80c825d68c6bf1020ab4317f2bce1efe16401b5b3280a181047c8317c38a19bbeeae8d52862e6b2c9776d5809758ee7aaa6
If you are updating the port, please update the hash in the port module.
notes/main/wasm/tools/buildMC.sh: line 10: build: command not found

The project updated their .hgignore file yesterday, which might be related.

https://github.com/libsdl-org/SDL_ttf/commit/19f5a6395382b0f7b206b2e9a18ebb240ddbd940

**Comment by kripken** [comment]
This has been fixed in emscripten by switching the port to github, after the libsdl.org server removed the builds. The fix is in 2.0.14, so an upgrade should fix things for you.

**Comment by HCLJason** [comment]
Thanks for the fast response! Is there a way for me to manually fix that on 2.0.13?

**Comment by sbc100** [comment]
Great.  Sorry for the inconvenience.    I guess we should probably try to avoid depending on external hosts that we don't control.

**Comment by gvanem** [comment]
> This has been fixed in emscripten by switching the port to github, 

I still have the issue with D/L from Github. My issue from yesterday:  https://github.com/ocornut/imgui/issues/4731.

And yes, I did run `emsdk.bat update` with no help.

**Comment by sbc100** [comment]
I just confirmed that https://github.com/emscripten-ports/SDL2/archive/version_24.zip does seem to have the correct hash:

```
$ wget https://github.com/emscripten-ports/SDL2/archive/version_24.zip
$ sha512sum  version_24.zip 
5a8181acdcce29cdda7e7a4cc876602740f5b9deebd366ecec71ae15c4bbf1f352da4dd0e3c5e0ba8160709dda0270566d64a6cd3892da894463ecf8502836aa  version_24.zip
$ git grep 5a8181acdc
tools/ports/sdl2.py:HASH = '5a8181acdcce29cdda7e7a4cc876602740f5b9deebd366ecec71ae15c4bbf1f352da4dd0e3c5e0ba8160709dda0270566d64a6cd3892da894463ecf8502836aa'
```

Perhaps there was some intermittent network issue.  Can you try again?

**Comment by gvanem** [comment]
> Can you try again?

Same error.
